[package]
name = "dupimg"
version = "1.0.0"
description = "A simple duplicate image finder"
categories = ["command-line-utilities", "multimedia::images"]
readme = true
repository = "https://github.com/DenebTM/dupimg"
license = "AGPL-3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
csv = "1.3.1"
image = "0.25.5"
image_hasher = "3.0.0"
imgref = "1.11.0"
itertools = "0.14.0"
num_cpus = "1.16.0"
rayon = "1.10.0"
shellexpand = "3.1.0"
walkdir = "2.5.0"
